name = "dev-cards-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Development environment
[env.development]
vars = { 
  ENVIRONMENT = "development",
  CORS_ORIGIN = "http://localhost:5173"
}

# Production environment
[env.production]
vars = { 
  ENVIRONMENT = "production",
  CORS_ORIGIN = "https://draw-it-play-it-ship-it.pages.dev"
}

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "dev-cards-db"
database_id = ""

# Production D1 database override
[env.production.d1_databases]
DB = { database_name = "dev-cards-db-prod", database_id = "" }

# Rate limiting with Durable Objects (optional for future use)
# [durable_objects]
# bindings = [
#   { name = "RATE_LIMITER", class_name = "RateLimiter", script_name = "rate-limiter" }
# ]

# KV namespace for caching (optional for future use)
# [[kv_namespaces]]
# binding = "CACHE"
# id = ""
# preview_id = ""

# Assets for static files (if needed)
# [assets]
# directory = "./public"
# binding = "ASSETS"