name = "dev-cards-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "dev-cards-db"
database_id = ""

[[d1_databases.env.production]]
binding = "DB"
database_name = "dev-cards-db-prod"
database_id = ""

# CORS settings
[env.development.vars]
CORS_ORIGIN = "http://localhost:5173"

[env.production.vars]
CORS_ORIGIN = "https://draw-it-play-it-ship-it.pages.dev"

# Rate limiting
[durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiter" }
]

# KV namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = ""
preview_id = ""
